name: Test Homebrew Formula

on:
  push:
    branches: master

jobs:
  test-formula:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew tap FastTrackOrg/fasttrack
          brew install fasttrack

      - name: Check GUI app exists
        run: |
          if [ ! -d "$(brew --prefix)/opt/fasttrack/libexec/fasttrack.app" ]; then
            echo "fasttrack.app not found!" >&2
            exit 1
          fi

      - name: Run CLI binary to verify install
        run: |
          fasttrack-cli --help

      - name: Symlink
        run: |
          ln -s "$(brew --prefix)/opt/fasttrack/libexec/fasttrack.app" /Applications/FastTrack.app
          [ -L /Applications/FastTrack.app ] && echo "Symlink created"
